In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
magic

In [4]:
%timeit 2**128

379 ns ± 17.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
%pwd

'/Users/xinliao/Projects/gitclone/python-excel'

In [6]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [7]:
lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [8]:
quickref

In [9]:
int_ones = np.ones((2,2), dtype=np.int8())

In [10]:
int_ones

array([[1, 1],
       [1, 1]], dtype=int8)

In [11]:
uint_ones = np.ones((2,2), dtype=np.uint8)
uint_ones

array([[1, 1],
       [1, 1]], dtype=uint8)

In [12]:
string_arr = np.array(['Sam', 'Bill', 'Gary'])

In [13]:
string_arr

array(['Sam', 'Bill', 'Gary'], dtype='<U4')

In [14]:
string_arr

array(['Sam', 'Bill', 'Gary'], dtype='<U4')

In [15]:
string_arr[1] = 'Waldo'

In [16]:
string_arr

array(['Sam', 'Wald', 'Gary'], dtype='<U4')

In [17]:
string_arr.isnull()

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'

In [18]:
np.isnan(string_str
    )

NameError: name 'string_str' is not defined

In [19]:
string_str

NameError: name 'string_str' is not defined

In [20]:
string_arr

array(['Sam', 'Wald', 'Gary'], dtype='<U4')

In [21]:
np.isnan(string_arr)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [22]:
string_arr.isnan()=

SyntaxError: cannot assign to function call (1462122697.py, line 1)

In [23]:
string_arr.isnan()

AttributeError: 'numpy.ndarray' object has no attribute 'isnan'

In [24]:
vec1 = np.array([1,1,0], dtype=np.floats)
vec2 = vec1 / 0
vec2

AttributeError: module 'numpy' has no attribute 'floats'

In [25]:
vec1 = np.array([1,1,0], dtype=np.float16)
vec2 = vec1 / 0
vec2

/var/folders/nf/wztbvlsd6zdbbhzd4ydxz3580000gn/T/ipykernel_26280/559495930.py:2: RuntimeWarning: divide by zero encountered in true_divide
  vec2 = vec1 / 0
/var/folders/nf/wztbvlsd6zdbbhzd4ydxz3580000gn/T/ipykernel_26280/559495930.py:2: RuntimeWarning: invalid value encountered in true_divide
  vec2 = vec1 / 0


array([inf, inf, nan], dtype=float16)

In [26]:
vec2

array([inf, inf, nan], dtype=float16)

In [27]:
np.isnan(vec2[2])

True

In [28]:
np.isinf(vec2[1])

True

In [29]:
inf + 1

inf

In [30]:
inf * -1

-inf

In [31]:
nana + 1

NameError: name 'nana' is not defined

In [32]:
nan + 1

nan

In [33]:
inf - inf

nan

In [34]:
vec4 = np.ones(5)
vec4[0] = np.nan
vec4

array([nan,  1.,  1.,  1.,  1.])

In [35]:
np.sum(vec4)

nan

In [36]:
np.nansum(vec4)

4.0

In [37]:
vec1 = np.ones((5))

In [38]:
vec1

array([1., 1., 1., 1., 1.])

In [39]:
vec1.dtype = np.int8

In [40]:
vec1

array([  0,   0,   0,   0,   0,   0, -16,  63,   0,   0,   0,   0,   0,
         0, -16,  63,   0,   0,   0,   0,   0,   0, -16,  63,   0,   0,
         0,   0,   0,   0, -16,  63,   0,   0,   0,   0,   0,   0, -16,
        63], dtype=int8)

In [41]:
vec1 = np.ones((5))

In [42]:
vec1 = np.array(vec1, dtype = np.int8)

In [43]:
vec1

array([1, 1, 1, 1, 1], dtype=int8)

In [44]:
vec1 = np.ones((5), dtype=np.int8)

In [45]:
vec1

array([1, 1, 1, 1, 1], dtype=int8)

In [46]:
arr1 = np.zeros((2,2,2), dtype=np.float64)

In [47]:
arr

NameError: name 'arr' is not defined

In [48]:
arr1

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [49]:
mat1 = np.random.randn(3,3)

In [50]:
mat1

array([[ 0.05606175, -0.2470723 , -0.64654917],
       [ 1.05293493, -0.2466404 , -1.41711847],
       [-0.60212667, -0.70860731, -0.30965959]])

In [51]:
mat2 = np.array([['bob', 'jane'], ['bill', 'janet']])

In [52]:
mat2

array([['bob', 'jane'],
       ['bill', 'janet']], dtype='<U5')

In [53]:
arr2 = np.array([[(1,3,5), (2,4,6)], [(1, np.nan, 1), (2,2,2)]])

In [54]:
arr2

array([[[ 1.,  3.,  5.],
        [ 2.,  4.,  6.]],

       [[ 1., nan,  1.],
        [ 2.,  2.,  2.]]])

In [55]:
mat2

array([['bob', 'jane'],
       ['bill', 'janet']], dtype='<U5')

In [56]:
mat2_cpy = mat2.copy()

In [57]:
mat2_cpy

array([['bob', 'jane'],
       ['bill', 'janet']], dtype='<U5')

In [58]:
arr1

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [59]:
np.save('arr1', arr1)

In [60]:
arr1_new = np.load('arr1.npy')

In [61]:
arr1_new

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [62]:
arr1_new

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [63]:
arr1 = np.array([[["Joe", 'Bob', "Sarah"], 
                  ['Margaret', "Rachel", "Jim"], 
                  ["Wayne", "Joey", "Liam"]],
                
                [["Max", "Maxine", "Richard"], 
                ["Harold", "Curtis", "Simon"],
                ["Bob", "Liam", "Simon"]],
                
                [["Wayne", "Sarah", "Lucy"],
                ["Lucy", "Kurtis", "Yu"],
                ["Joey", "Lex", "Alex"]]])

In [64]:
arr1

array([[['Joe', 'Bob', 'Sarah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joey', 'Lex', 'Alex']]], dtype='<U8')

In [65]:
arr2 = arr1[:, : ,0].copy()

In [66]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [67]:
print(arr2[[1,1,1,0,2], [0,1,2,1,1]])

['Max' 'Harold' 'Bob' 'Margaret' 'Lucy']


In [68]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [69]:
arr2[:2, :2]

array([['Joe', 'Margaret'],
       ['Max', 'Harold']], dtype='<U8')

In [70]:
print(arr2[:, 1])

['Margaret' 'Harold' 'Lucy']


In [71]:
print(arr2[:, [1]])

[['Margaret']
 ['Harold']
 ['Lucy']]


In [72]:
print(arr2[::-1, :])

[['Wayne' 'Lucy' 'Joey']
 ['Max' 'Harold' 'Bob']
 ['Joe' 'Margaret' 'Wayne']]


In [73]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [74]:
print(arr2[:, 0:3:2])

[['Joe' 'Wayne']
 ['Max' 'Bob']
 ['Wayne' 'Joey']]


In [75]:
print(arr1[0:2, 0:2, 0:2])

[[['Joe' 'Bob']
  ['Margaret' 'Rachel']]

 [['Max' 'Maxine']
  ['Harold' 'Curtis']]]


In [76]:
arr1

array([[['Joe', 'Bob', 'Sarah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joey', 'Lex', 'Alex']]], dtype='<U8')

In [77]:
print(arr1[:, 1, :])

[['Margaret' 'Rachel' 'Jim']
 ['Harold' 'Curtis' 'Simon']
 ['Lucy' 'Kurtis' 'Yu']]


In [78]:
arr1[:, 1, np.newasix, :]

AttributeError: module 'numpy' has no attribute 'newasix'

In [79]:
arr1[:, 1, np.newaxis, :]

array([[['Margaret', 'Rachel', 'Jim']],

       [['Harold', 'Curtis', 'Simon']],

       [['Lucy', 'Kurtis', 'Yu']]], dtype='<U8')

In [80]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [81]:
print(arr2[arr2 != 'Wayne'])

['Joe' 'Margaret' 'Max' 'Harold' 'Bob' 'Lucy' 'Joey']


In [82]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [83]:
print(arr2 != 'Wayne')

[[ True  True False]
 [ True  True  True]
 [False  True  True]]


In [84]:
idx0 = np.array([[0, 0],
                [2, -2]])

In [85]:
idx1 = np.array([[0, 2],
                [0, 2]])

In [86]:
idx0

array([[ 0,  0],
       [ 2, -2]])

In [87]:
idx1

array([[0, 2],
       [0, 2]])

In [88]:
arr1

array([[['Joe', 'Bob', 'Sarah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joey', 'Lex', 'Alex']]], dtype='<U8')

In [89]:
arr1[arr1 != 'Curtis']

array(['Joe', 'Bob', 'Sarah', 'Margaret', 'Rachel', 'Jim', 'Wayne',
       'Joey', 'Liam', 'Max', 'Maxine', 'Richard', 'Harold', 'Simon',
       'Bob', 'Liam', 'Simon', 'Wayne', 'Sarah', 'Lucy', 'Lucy', 'Kurtis',
       'Yu', 'Joey', 'Lex', 'Alex'], dtype='<U8')

In [90]:
print(arr1 != 'Curtis')

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True False  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [91]:
coord

NameError: name 'coord' is not defined

In [92]:
from numpy.random import randn

In [93]:
import numpy.linalg as ln

In [94]:
ln

<module 'numpy.linalg' from '/Users/xinliao/opt/anaconda3/lib/python3.9/site-packages/numpy/linalg/__init__.py'>

In [95]:
arr1 = np.array(randn(3,3,3) * 10, dtype=np.int64)

In [96]:
arr2 = np.array(randn(3,3,3) * 10, dtype = np.int64)

In [97]:
arr1
arr2

array([[[  4,   0,   5],
        [ -7,   1, -12],
        [  4,  -4,   1]],

       [[ 15,   0,   3],
        [ -4,   8,  18],
        [  2,   3,   7]],

       [[  3,   7,  -3],
        [  2,  10,   0],
        [-15,   4, -15]]])

In [98]:
arr1

array([[[  6, -14,  -2],
        [ -2,  -6,  -8],
        [ 11,  -1,   9]],

       [[-16, -13,  -6],
        [  5,   2, -10],
        [  1,  -1, -13]],

       [[  0,   3,   4],
        [  1, -10,   0],
        [  5,  -3,  -6]]])

In [99]:
arr2

array([[[  4,   0,   5],
        [ -7,   1, -12],
        [  4,  -4,   1]],

       [[ 15,   0,   3],
        [ -4,   8,  18],
        [  2,   3,   7]],

       [[  3,   7,  -3],
        [  2,  10,   0],
        [-15,   4, -15]]])

In [100]:
arr1 + 100

array([[[106,  86,  98],
        [ 98,  94,  92],
        [111,  99, 109]],

       [[ 84,  87,  94],
        [105, 102,  90],
        [101,  99,  87]],

       [[100, 103, 104],
        [101,  90, 100],
        [105,  97,  94]]])

In [101]:
arr1 / 2

array([[[ 3. , -7. , -1. ],
        [-1. , -3. , -4. ],
        [ 5.5, -0.5,  4.5]],

       [[-8. , -6.5, -3. ],
        [ 2.5,  1. , -5. ],
        [ 0.5, -0.5, -6.5]],

       [[ 0. ,  1.5,  2. ],
        [ 0.5, -5. ,  0. ],
        [ 2.5, -1.5, -3. ]]])

In [102]:
arr2 ** 2

array([[[ 16,   0,  25],
        [ 49,   1, 144],
        [ 16,  16,   1]],

       [[225,   0,   9],
        [ 16,  64, 324],
        [  4,   9,  49]],

       [[  9,  49,   9],
        [  4, 100,   0],
        [225,  16, 225]]])

In [103]:
arr1 

array([[[  6, -14,  -2],
        [ -2,  -6,  -8],
        [ 11,  -1,   9]],

       [[-16, -13,  -6],
        [  5,   2, -10],
        [  1,  -1, -13]],

       [[  0,   3,   4],
        [  1, -10,   0],
        [  5,  -3,  -6]]])

In [104]:
arr2

array([[[  4,   0,   5],
        [ -7,   1, -12],
        [  4,  -4,   1]],

       [[ 15,   0,   3],
        [ -4,   8,  18],
        [  2,   3,   7]],

       [[  3,   7,  -3],
        [  2,  10,   0],
        [-15,   4, -15]]])

In [105]:
arr1 * arr2

array([[[  24,    0,  -10],
        [  14,   -6,   96],
        [  44,    4,    9]],

       [[-240,    0,  -18],
        [ -20,   16, -180],
        [   2,   -3,  -91]],

       [[   0,   21,  -12],
        [   2, -100,    0],
        [ -75,  -12,   90]]])

In [106]:
arr1 * arr2

array([[[  24,    0,  -10],
        [  14,   -6,   96],
        [  44,    4,    9]],

       [[-240,    0,  -18],
        [ -20,   16, -180],
        [   2,   -3,  -91]],

       [[   0,   21,  -12],
        [   2, -100,    0],
        [ -75,  -12,   90]]])

In [107]:
arr1 ** (arr2/4)

/var/folders/nf/wztbvlsd6zdbbhzd4ydxz3580000gn/T/ipykernel_26280/2823582803.py:1: RuntimeWarning: invalid value encountered in power
  arr1 ** (arr2/4)


array([[[ 6.00000000e+00,  1.00000000e+00,             nan],
        [            nan,             nan, -1.95312500e-03],
        [ 1.10000000e+01, -1.00000000e+00,  1.73205081e+00]],

       [[            nan,  1.00000000e+00,             nan],
        [ 2.00000000e-01,  4.00000000e+00,             nan],
        [ 1.00000000e+00,             nan,             nan]],

       [[ 0.00000000e+00,  6.83852117e+00,  3.53553391e-01],
        [ 1.00000000e+00,             nan,  1.00000000e+00],
        [ 2.39255805e-03, -3.00000000e+00,             nan]]])

In [108]:
print (arr3.shape)

NameError: name 'arr3' is not defined

In [109]:
arr3 = np.array(randn(4,4) * 10, dtype=np.int8)

In [110]:
arr3

array([[ -3,   8, -10,  14],
       [ -5,   9, -14,  -7],
       [  7,  -6, -15,   9],
       [ -4,   3,   4,  -7]], dtype=int8)

In [111]:
arr1.tolist()

[[[6, -14, -2], [-2, -6, -8], [11, -1, 9]],
 [[-16, -13, -6], [5, 2, -10], [1, -1, -13]],
 [[0, 3, 4], [1, -10, 0], [5, -3, -6]]]

In [112]:
arr2 = np.empty((4,3), dtype=np.dtype('<U15'))

In [113]:
arr2

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U15')

In [114]:
arr2.fill('Carlos')

In [115]:
arr2

array([['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos']], dtype='<U15')

In [116]:
arr1.sum()

-64

In [117]:
arr1.sum(axis = 0)

array([[-10, -24,  -4],
       [  4, -14, -18],
       [ 17,  -5, -10]])

In [118]:
arr1

array([[[  6, -14,  -2],
        [ -2,  -6,  -8],
        [ 11,  -1,   9]],

       [[-16, -13,  -6],
        [  5,   2, -10],
        [  1,  -1, -13]],

       [[  0,   3,   4],
        [  1, -10,   0],
        [  5,  -3,  -6]]])

In [119]:
arr2

array([['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos']], dtype='<U15')

In [120]:
arr1 =np.array(randn(4, 4) * 10, dtype = np.uint8)

In [121]:
arr1

array([[247, 252,   5,  18],
       [242, 253, 252, 247],
       [ 13,   1, 253, 241],
       [244, 248,   1,   1]], dtype=uint8)

In [122]:
arr1 = np.array(randn(4,4), dtype = np.int8)

In [123]:
arr1

array([[ 0,  0,  1,  0],
       [ 0,  0,  1,  0],
       [ 0,  0,  1,  0],
       [ 0, -1,  0,  0]], dtype=int8)