In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
%timeit 2**128

406 ns ± 14.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
%pwd

'/Users/xinliao/Projects/gitclone/python-excel'

In [5]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [6]:
int_ones = np.ones((2,2), dtype=np.int8())

In [7]:
int_ones

array([[1, 1],
       [1, 1]], dtype=int8)

In [8]:
uint_ones = np.ones((2,2), dtype=np.uint8)
uint_ones

array([[1, 1],
       [1, 1]], dtype=uint8)

In [9]:
string_arr = np.array(['Sam', 'Bill', 'Gary'])

In [10]:
string_arr

array(['Sam', 'Bill', 'Gary'], dtype='<U4')

In [11]:
string_arr

array(['Sam', 'Bill', 'Gary'], dtype='<U4')

In [12]:
string_arr[1] = 'Waldo'

In [13]:
string_arr

array(['Sam', 'Wald', 'Gary'], dtype='<U4')

In [14]:
string_arr

array(['Sam', 'Wald', 'Gary'], dtype='<U4')

In [15]:
inf + 1

inf

In [16]:
inf * -1

-inf

In [17]:
nan + 1

nan

In [18]:
inf - inf

nan

In [19]:
vec4 = np.ones(5)
vec4[0] = np.nan
vec4

array([nan,  1.,  1.,  1.,  1.])

In [20]:
np.sum(vec4)

nan

In [21]:
np.nansum(vec4)

4.0

In [22]:
vec1 = np.ones((5))

In [23]:
vec1

array([1., 1., 1., 1., 1.])

In [24]:
vec1.dtype = np.int8

In [25]:
vec1

array([  0,   0,   0,   0,   0,   0, -16,  63,   0,   0,   0,   0,   0,
         0, -16,  63,   0,   0,   0,   0,   0,   0, -16,  63,   0,   0,
         0,   0,   0,   0, -16,  63,   0,   0,   0,   0,   0,   0, -16,
        63], dtype=int8)

In [26]:
vec1 = np.ones((5))

In [27]:
vec1 = np.array(vec1, dtype = np.int8)

In [28]:
vec1

array([1, 1, 1, 1, 1], dtype=int8)

In [29]:
vec1 = np.ones((5), dtype=np.int8)

In [30]:
vec1

array([1, 1, 1, 1, 1], dtype=int8)

In [31]:
arr1 = np.zeros((2,2,2), dtype=np.float64)

In [32]:
arr1

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [33]:
mat1 = np.random.randn(3,3)

In [34]:
mat1

array([[ 0.75022374,  1.07384072, -0.62613052],
       [ 0.18851496,  1.33711173,  0.29006489],
       [ 0.26875612,  1.72859086, -0.83195116]])

In [35]:
mat2 = np.array([['bob', 'jane'], ['bill', 'janet']])

In [36]:
mat2

array([['bob', 'jane'],
       ['bill', 'janet']], dtype='<U5')

In [37]:
arr2 = np.array([[(1,3,5), (2,4,6)], [(1, np.nan, 1), (2,2,2)]])

In [38]:
arr2

array([[[ 1.,  3.,  5.],
        [ 2.,  4.,  6.]],

       [[ 1., nan,  1.],
        [ 2.,  2.,  2.]]])

In [39]:
mat2

array([['bob', 'jane'],
       ['bill', 'janet']], dtype='<U5')

In [40]:
mat2_cpy = mat2.copy()

In [41]:
mat2_cpy

array([['bob', 'jane'],
       ['bill', 'janet']], dtype='<U5')

In [42]:
arr1

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [43]:
np.save('arr1', arr1)

In [44]:
arr1_new = np.load('arr1.npy')

In [45]:
arr1_new

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [46]:
arr1_new

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [47]:
arr1 = np.array([[["Joe", 'Bob', "Sarah"], 
                  ['Margaret', "Rachel", "Jim"], 
                  ["Wayne", "Joey", "Liam"]],
                
                [["Max", "Maxine", "Richard"], 
                ["Harold", "Curtis", "Simon"],
                ["Bob", "Liam", "Simon"]],
                
                [["Wayne", "Sarah", "Lucy"],
                ["Lucy", "Kurtis", "Yu"],
                ["Joey", "Lex", "Alex"]]])

In [48]:
arr1

array([[['Joe', 'Bob', 'Sarah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joey', 'Lex', 'Alex']]], dtype='<U8')

In [49]:
arr2 = arr1[:, : ,0].copy()

In [50]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [51]:
print(arr2[[1,1,1,0,2], [0,1,2,1,1]])

['Max' 'Harold' 'Bob' 'Margaret' 'Lucy']


In [52]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [53]:
arr2[:2, :2]

array([['Joe', 'Margaret'],
       ['Max', 'Harold']], dtype='<U8')

In [54]:
print(arr2[:, 1])

['Margaret' 'Harold' 'Lucy']


In [55]:
print(arr2[:, [1]])

[['Margaret']
 ['Harold']
 ['Lucy']]


In [56]:
print(arr2[::-1, :])

[['Wayne' 'Lucy' 'Joey']
 ['Max' 'Harold' 'Bob']
 ['Joe' 'Margaret' 'Wayne']]


In [57]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [58]:
print(arr2[:, 0:3:2])

[['Joe' 'Wayne']
 ['Max' 'Bob']
 ['Wayne' 'Joey']]


In [59]:
print(arr1[0:2, 0:2, 0:2])

[[['Joe' 'Bob']
  ['Margaret' 'Rachel']]

 [['Max' 'Maxine']
  ['Harold' 'Curtis']]]


In [60]:
arr1

array([[['Joe', 'Bob', 'Sarah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joey', 'Lex', 'Alex']]], dtype='<U8')

In [61]:
print(arr1[:, 1, :])

[['Margaret' 'Rachel' 'Jim']
 ['Harold' 'Curtis' 'Simon']
 ['Lucy' 'Kurtis' 'Yu']]


In [62]:
arr1[:, 1, np.newaxis, :]

array([[['Margaret', 'Rachel', 'Jim']],

       [['Harold', 'Curtis', 'Simon']],

       [['Lucy', 'Kurtis', 'Yu']]], dtype='<U8')

In [63]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [64]:
print(arr2[arr2 != 'Wayne'])

['Joe' 'Margaret' 'Max' 'Harold' 'Bob' 'Lucy' 'Joey']


In [65]:
arr2

array([['Joe', 'Margaret', 'Wayne'],
       ['Max', 'Harold', 'Bob'],
       ['Wayne', 'Lucy', 'Joey']], dtype='<U8')

In [66]:
print(arr2 != 'Wayne')

[[ True  True False]
 [ True  True  True]
 [False  True  True]]


In [67]:
idx0 = np.array([[0, 0],
                [2, -2]])

In [68]:
idx1 = np.array([[0, 2],
                [0, 2]])

In [69]:
idx0

array([[ 0,  0],
       [ 2, -2]])

In [70]:
idx1

array([[0, 2],
       [0, 2]])

In [71]:
arr1

array([[['Joe', 'Bob', 'Sarah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joey', 'Lex', 'Alex']]], dtype='<U8')

In [72]:
arr1[arr1 != 'Curtis']

array(['Joe', 'Bob', 'Sarah', 'Margaret', 'Rachel', 'Jim', 'Wayne',
       'Joey', 'Liam', 'Max', 'Maxine', 'Richard', 'Harold', 'Simon',
       'Bob', 'Liam', 'Simon', 'Wayne', 'Sarah', 'Lucy', 'Lucy', 'Kurtis',
       'Yu', 'Joey', 'Lex', 'Alex'], dtype='<U8')

In [73]:
print(arr1 != 'Curtis')

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True False  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [74]:
coord

NameError: name 'coord' is not defined

In [ ]:
from numpy.random import randn

In [ ]:
import numpy.linalg as ln

In [ ]:
ln

In [ ]:
arr1 = np.array(randn(3,3,3) * 10, dtype=np.int64)

In [ ]:
arr2 = np.array(randn(3,3,3) * 10, dtype = np.int64)

In [ ]:
arr1
arr2

In [ ]:
arr1 + 100

In [ ]:
arr1 / 2

In [ ]:
arr2 ** 2

In [ ]:
arr1 

In [ ]:
arr2

In [ ]:
arr3 = np.array(randn(4,4) * 10, dtype=np.int8)

In [ ]:
arr3

In [ ]:
arr1.tolist()

In [ ]:
arr2 = np.empty((4,3), dtype=np.dtype('<U15'))

In [ ]:
arr2

In [ ]:
arr2.fill('Carlos')

In [ ]:
arr2

In [ ]:
arr1.sum()

In [ ]:
arr1.sum(axis = 0)

In [ ]:
arr1

In [ ]:
arr1 =np.array(randn(4, 4) * 10, dtype = np.uint8)

In [ ]:
arr1

In [ ]:
arr1 = np.array(randn(4,4), dtype = np.int8)

In [75]:
arr1

array([[['Joe', 'Bob', 'Sarah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joey', 'Lex', 'Alex']]], dtype='<U8')

In [76]:
pd

<module 'pandas' from '/Users/xinliao/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py'>